BEGIN;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS topic;
DROP TABLE IF EXISTS comment;

CREATE TABLE user (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE topic (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT REFERENCES user(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE comment (
  id SERIAL PRIMARY KEY NOT NULL,
  topic_id INT REFERENCES topic(id) ON DELETE CASCADE,
  user_id INT REFERENCES user(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;
